version: '2'
services:
    poc-app:
        image: poc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@poc-oracle:1521:poc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8089:8089
